--- #creating war file on maven machine
- hosts: maven
  user: ec2-user
  become: yes
  connection: ssh
  gather_facts: yes
  tasks:
    - name: creating new folder for cloning game of life
      action: file path=/mnt/app state=directory mode='0777'
    - name: installing git
      action: yum pkg=git state=present
      
    - name: cloning repo
      action: git repo=https://github.com/anilbichkule/game-of-life.git dest=/mnt/app

    - name: installing maven
      get_url:
        url: https://repos.fedorapeople.org/repos/dchen/apache-maven/epel-apache-maven.repo
        dest: /etc/yum.repos.d


    - name: install maven
      yum:
        name: maven
        state: present

    - name: run project using maven
      command: " mvn clean install "
      become: yes
      args:
        chdir: /mnt/app

    - name: fetching war file in the ansible server
      action: fetch src=/mnt/app/gameoflife-web/target/gameoflife.war dest=/mnt/app/deployment

